TrajectoryPlannerROS:
  max_vel_x: 0.34
  min_vel_x: 0.1
  max_vel_y: 0.1
  min_vel_y: -0.1
  max_rot_vel: 1.0
  max_rot_vel: 0.4
  max_vel_trans: 0.55
  min_vel_trans: 0.1
  max_vel_theta: 0.4
  min_vel_theta: -0.4
  min_in_place_vel_theta: 0.15
  backup_vel: -0.1

  acc_lim_theta: 3.2
  acc_lim_x: 2.5
  acc_lim_y: 2.5

  holonomic_robot: false

  xy_goal_tolerance:  0.20
  yaw_goal_tolerance: 0.20

  meter_scoring: true

