TrajectoryPlannerROS:
  max_vel_x: 0.34
  min_vel_x: 0
  max_vel_y: 0
  min_vel_y: 0
  max_vel_theta: 0.76
  min_in_place_vel_theta: 0.15
  backup_vel: -0.3

  acc_lim_theta: 3.2
  acc_lim_x: 2.5
  acc_lim_y: 2.5

  holonomic_robot: false

  xy_goal_tolerance:  0.20
  yaw_goal_tolerance: 0.20

  sim_time: 1.7
  sim_granularity: 0.025
  vx_samples: 3
  vtheta_samples: 20

  goal_distance_bias: 0.8
  path_distance_bias: 0.6
  occdist_scale: 0.01
  heading_lookahead: 0.325
  dwa: false

  oscillation_reset_dist: 0.05
  meter_scoring: true
